# Generated by Django 4.0.4 on 2022-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.IntegerField(default=0, verbose_name='time taken')),
                ('description', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
