# Generated by Django 4.0.4 on 2022-05-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='time_est',
            new_name='date',
        ),
    ]
